### ISSUE TITLE
Will not even run - and throws

### ISSUE THREAD

**Issue by crazyhuggins** [Inist-CNRS/node-inotifywait#5]
@kerphi 

```js
var INotifyWait = require('./index');

var watch1 = new INotifyWait(__dirname, { recursive: false });
```

**result**

```js
Error: spawn inotifywait ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:609:11)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

**Comment by kerphi** [comment]
It could not work on windows cause inotifywait program does not exists (as i know)
